### ISSUE TITLE
Great! One small wish...

### ISSUE THREAD

**Issue by callimero** [Blokatt/FX4Reaper#2]
I used your fine plugin so far only for making parameter images for my patches collection, but hell thats so much eassier as taking notes or pictures :) https://github.com/callimero/Monologue

One small thing: Could you include the name of the loaded patch in the Window? E.g. above or beneath "Program:" Slider?

I know I can look at the bottom, but thats tiny and very crowded there.

**Comment by Blokatt** [comment]
I'm afraid that's not possible due to limitations of JSFX. If the language is ever updated to allow this, I'd implement it by all means, but for now, there's nothing I can do other than print the name in the bottom window.

**Comment by callimero** [comment]
Maybe put it somewhat bigger into the bottom window? :)

**Comment by Blokatt** [comment]
Could be done, just gotta find an aesthetically pleasing place for it first.
It's actually sort of implemented in the code, but commented out. 
https://github.com/Blokatt/FX4Reaper/blob/b6e08575d4f3afa5fd087e2a2a1a49a0c02ca8a4/monoctrl/monoctrl/monoctrl#L1199-L1206

**Comment by callimero** [comment]
Ah, did not expect a scripting language :) 

Thats great!
